### ISSUE TITLE
Dealing with S3 bucket url changing + signs to %2B

### ISSUE THREAD

**Issue by HunterMillerc** [Malvineous/archlinux-pacman-repo#1]
Have you ran into the issue of packages containing + signs being converted to %2B in the S3 URL?

https://bbs.archlinux.org/viewtopic.php?id=279269.

Wondering if you have found a workaround rather than using a custom XferCommand to fix the issue.

**Comment by Malvineous** [comment]
I haven't yet tried to publish a package with a `+` in the name.  Is that symbol allowed in the path component of the URL?  Normally it's used in the query string but I'm not sure what the rules are about it appearing in the path component.

**Comment by Malvineous** [comment]
It sort of works if I put a redirection rule on the S3 bucket for the specific filename itself:
```
    {
        "Condition": {
            "KeyPrefixEquals": "test+"
        },
        "Redirect": {
            "ReplaceKeyPrefixWith": "test%2B"
        }
    },
```
This makes `test+ing.txt` redirect to `test%2Bing.txt` which works.  But it only seems to work when I access the bucket directly.  If I go through CloudFront it doesn't work.

I suspect the solution would be to add a Lambda@Edge function to CloudFront that replaces `+` with `%2B` on incoming requests before CloudFront passes them to the S3 bucket.

**Comment by HunterMillerc** [comment]
Fixed utilizing Cloudfront function:
```
function handler(event) {
    var request = event.request;
    var uri = request.uri;
    // Change + signs to %2B in the request uri
    if (uri.includes('+')) {
        request.uri = request.uri.replace(/\+/g, '%2B');
    }
    return request;
}
```

Thanks for the idea!
